### ISSUE TITLE
Navbar - Add a link to HB Youtube Channel

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#15]
Why not ?

**Comment by zugspitze** [comment]
Nav bar or Footer?

**Comment by Galven** [comment]
I'd say navbar, near the Blog Button. Well, for now it does not matter a lot. But even if there's not a lot of content currently, it could become more important in the future.

Oh, and I just saw the FAQs button ... Don't you think it would be better to put it in the Navbar as well ?

**Comment by zugspitze** [comment]
Usually FAQs are put in the Footer, I think if we put everything in the Navbar, it will become bulky. We should keep only very important things in the Navbar. 

We can put YouTube channel link in the Navbar [under help link ?], people can use that to see how to use the website. Also, we need someone who can add more tutorial videos.

**Comment by Galven** [comment]
Okay let's do it this way.
Maybe we should wait for tutorials... You talked about changing the whole event page for example.

**Comment by zugspitze** [comment]
Yeah, let's wait for those changes.
