### ISSUE TITLE
General - Rename "Difficulty" to "Technical Difficulty"

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#16]
It became quite common for people to say "why is this route qualified as easy when it's 30km and 3000m D+ ????"

So it would be better to add rename it "Technical difficulty" everywhere, wouldn't it ?

**Comment by zugspitze** [comment]
@Galven Renaming is simple fix.

However, I think most of the routes in Chile have no SAC scale data. If the sac-scale isn't there, it assumes technical difficulty to be "very easy".

It's possible for me to add SAC scale to any route. But I don't know the SAC scales there. If you can provide me that, I can also add sac scale to all routes in Chile.

**Comment by Galven** [comment]
All the routes I've added in Chile have nothing difficult technically (I'd say SAC Scale 2 for all of them). So the rating "easy" is correct if we refer to the technical part. Other routes that I haven't done (I'm not into via ferratas ... yet) do have technical part, but for now there is none registered on the website.

It's really just the term "difficulty" that is '''annoying''' / not the best. When talking about difficulty, people think first about their legs, and not the technical part ;-). So it'd be better to name it "technical difficulty" instead of just "difficulty".

**Comment by zugspitze** [comment]
Sounds good, less work for me ;-)

**Comment by zugspitze** [comment]
Let's make a list of places where we have to change "Difficulty" to "Technical Difficulty"
1. Route page
2. Route list page
3. Filter in route list page
4. Event page
