### ISSUE TITLE
Events List - Add fields # Participants, # Waitlisted, # Limit of participants

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#19]
Could you please add those three columns to the events list, so that we can know quickly which are the events that are full / not full?

- Limit of participants
- Number of participants
- Number of waitlisted

![captura](https://user-images.githubusercontent.com/40529268/42052608-bc2e172c-7afe-11e8-99a3-aeb6838aa33b.JPG)

**Comment by zugspitze** [comment]
Yeah, that's a good suggestion. Currently many people ask about free places.
