### ISSUE TITLE
No country or region info in routes

### ISSUE THREAD

**Issue by marceloepires** [zugspitze/Hiking-Buddies#2]
As multinational platform it is good to have the Country / Region of each hiking on routes on the list

![image](https://user-images.githubusercontent.com/18307756/41315318-6e9306ec-6e8f-11e8-8645-d105c7a12384.png)

**Comment by zugspitze** [comment]
I think if we put country and region, the list will become too big. And since there is a filter based on country, most users will check for only one country. Also we have routes with map view where you can see the exact region and country of routes.
