### ISSUE TITLE
Blog explaining sac scales and requirements

### ISSUE THREAD

**Issue by zugspitze** [zugspitze/Hiking-Buddies#26]
I think many people are not familiar with sac scales. I think it would be nice to have a blog explaining sac scale and the requirements for each of them also some examples. 

Something like this:
https://wiki.openstreetmap.org/wiki/Key:sac_scale

**Comment by zugspitze** [comment]
@Galven if you haven't started writing this blog. Thomas told me today he is writing the blog. Probably you can simply modify his blog when he submit it for review.

**Comment by Galven** [comment]
I actually had started something, but it's fine if he does it

**Comment by zugspitze** [comment]
Ohh, sorry for miscommunications from my side. You can edit/modify/polish his blog when he submits for review.
