### ISSUE TITLE
Event description - Horizontal bar does not appear

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#28]
1 - Putting a horizontal bar while writing the description

![1](https://user-images.githubusercontent.com/40529268/42286226-2c85f5c8-7f80-11e8-9f2f-26f33efe6a11.JPG)

2 - Not appearing after saving

![2](https://user-images.githubusercontent.com/40529268/42286262-460b8472-7f80-11e8-89ac-746987bee744.JPG)

**Comment by zugspitze** [comment]
@Galven But the text goes to the next line automatically or not? If so, we don't need the horizontal bar.

**Comment by Galven** [comment]
Yes it does, but horizontal bar for separating main parts looked pretty 
Okay I close the issue if we don't care about the horizontal bar :D

**Comment by zugspitze** [comment]
Ahh, now I get what you mean. I was confusing with horizontal scroll bar ;-) I will check for it.

**Comment by c-harding** [comment]
This seems to be fixed in the new event page

**Comment by zugspitze** [comment]
Cool, I close the issue then
