### ISSUE TITLE
General - Karma Points

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#33]
In addition to the current rating representing each Buddy's physical condition (based on passed hikes), a Karma system will aim at representing their contribution for the Hiking Buddies community.

It will take into account:

- Number of **organized events** (fixed Karma points per event)
- Number of **participant reviews** added to other Buddies (fixed Karma points per review)
- Number of **routes** added. If technically possible, Karma points should be higher for well detailed routes.
- Number of **route reviews** added (when the functionality will be available).
- Number of **blogs** written (fixed Karma points per blog)

**Comment by zugspitze** [comment]
Blogs written?

**Comment by c-harding** [comment]
Resolved?
