### ISSUE TITLE
loading insecure (over http) google stylesheets is blocked

### ISSUE THREAD

**Issue by marian-gheorghe** [zugspitze/Hiking-Buddies#40]
Search for an user : Amit Verma (the left hands side block contains blocked /broken CSS)
Open developer console 
Mixed Content: The page at 'https://www.hiking-buddies.com/routes/search?q=frolova' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:300,400,500,700'. This request has been blocked; the content must be served over HTTPS.

**Comment by zugspitze** [comment]
Can you please verify if the problem persist?

**Comment by marian-gheorghe** [comment]
fixed
