### ISSUE TITLE
Past hikes not in correct order in user profile

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#66]
Past hikes not in correct order
Example for myself https://www.hiking-buddies.com/routes/user/19/

Jan 08 2022
Jan 05 2022
Jan 06 2022
> Mixed up

Should be
Jan 08 2022
Jan 06 2022
Jan 05 2022

![image](https://user-images.githubusercontent.com/40529268/149649566-4c6f4e30-a95d-458e-b0a5-c2e918fcaf45.png)

**Comment by zugspitze** [comment]
Should be fixed now!

**Comment by Galven** [comment]
Yes it works 👍
