### ISSUE TITLE
Event description - Remove "Show more"

### ISSUE THREAD

**Issue by Galven** [zugspitze/Hiking-Buddies#73]
On Android (at least), the description goes back  to Show less mode when scrolling down.
As agreed, since the description is more important than the comments, a quick fix will be to always show the entire event description.

**Comment by zugspitze** [comment]
Removed "Read more" option

**Comment by zugspitze** [comment]
Sorry, introduced a bug, reverting...
Will fix properly later

**Comment by zugspitze** [comment]
Finally done properly without bug
