### ISSUE TITLE
new android app: incorrect profile in the home screen.

### ISSUE THREAD

**Issue by omarnasr** [zugspitze/Hiking-Buddies#87]
1. Open any event from the home screen
2. go to participant list
3. open profile of any participant
4. go back to home screen.
5. the profile displayed on the top will be the profile of the participant instead of the logged in participant.

check attachment. profile of Amir displayed instead of Omar.
![423147284_918380633251147_3425732433474187977_n](https://github.com/zugspitze/Hiking-Buddies/assets/19608015/b79ce743-8982-4728-944d-87e11497c99c)

**Comment by zugspitze** [comment]
I think this is fixed, can you confirm?

**Comment by omarnasr** [comment]
yes fixed
